### ISSUE TITLE
Gestion des Todo

### ISSUE THREAD

**Issue by christmknd** [christmknd/ToDoList#4]
- [ ] - **Créer une Todo** (`createTodo(userId, data)`): Créer un nouveau Todo pour un utilisateur.
- [ ] - **Lire une Todo** (`getTodoById(id)`): Récupérer les détails d'un Todo par son ID.
- [ ] - **Mettre à jour une Todo** (`updateTodo(id, data)`): Modifier les informations d'un Todo (nom, description, etc.).
- [ ] - **Supprimer une Todo** (`deleteTodo(id)`): Supprimer un Todo.
- [ ] - **Lister les Todos d'un utilisateur** (`getAllTodosByUser(userId)`): Récupérer toutes les Todos d'un utilisateur ⇒ accessible que par l’utilisateur connecté ou par l’admin
- [ ] - **Lister l’ensemble Todos** (`getAllTodosByUser()`): Récupérer toutes les Todos
